# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
# https://github.com/apache/cordova-plugin-contacts/blob/master/.appveyor.yml
# https://www.appveyor.com/docs/build-environment/


init:
  - git config --global core.autocrlf true

image:
  - Ubuntu1804

environment:
  nodejs_version: "12"
  
install:
  - npm cache clean -f
  - nvm install 12
  - node --version
  - npm install -g cordova
  - npm install -g cordova-res
  - sudo apt update 
  - sudo apt install android-sdk -y
  - sudo apt install libsecret-1-dev -y

build_script: 
  - npm install
  - npx ionic cordova platform add android --verbose
  - cordova-res android --skip-config --copy
  - cp -Rv android platforms/android 
  - npx cordova prepare
  - npx gulp
  - npm run ionic:build -- --prod
  - npx cordova build android --aot


