# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
# https://github.com/apache/cordova-plugin-contacts/blob/master/.appveyor.yml
# https://www.appveyor.com/docs/build-environment/


init:
  - git config --global core.autocrlf true

image:
  - Ubuntu1804

environment:
  nodejs_version: "12"
  
install:
  - npm cache clean -f
  - nvm install 12
  - node --version
  - npm install -g cordova
  - npm install -g cordova-res
  - sudo apt update 
  - sudo apt install android-sdk -y
  - sudo apt install libsecret-1-dev -y
#  - tar -xf  jdk-8u341-linux-x64.tar.gz
  - 7z x jarchive.zip
# unfortunately, just setting JAVA_HOME doesn't seem to be enough
# We need to use update-alternatives, both now
# to set to java8 and perhaps later to set back to 11?
# for android build?
# So, abandoning appveyor in favour of travis
# for which moodleapp repo has travis.yml already. 
  - export JAVA_HOME="$HOME/jdk1.8.0_341"
  - export PATH=$JAVA_HOME/bin:$PATH
  - export ANDROID_SDK_ROOT=/usr/lib/android-sdk
  - export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH 

build_script: 
  - npm install
  - npx ionic cordova platform add android --verbose
  - cordova-res android --skip-config --copy
  - cp -Rv android platforms/android 
  - npx cordova platform remove ios
  - npx cordova prepare
  - npx gulp
#  - npm run ionic:build -- --prod
  - npx cordova build android --aot

artifacts:
  - path: platforms/android/app/build/outputs
